# Generated by Django 3.2.5 on 2022-05-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='latestoffers_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=1024)),
                ('email', models.EmailField(default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='userfaceid',
            fields=[
                ('id_face', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=1024, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('username', models.CharField(default='', max_length=1024, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=1024)),
                ('email', models.EmailField(default='', max_length=1024, unique=True)),
                ('contact', models.CharField(default='', max_length=12, unique=True)),
                ('head_shot', models.ImageField(blank=True, default='', upload_to='user_face_images/')),
            ],
        ),
        migrations.CreateModel(
            name='userrequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=1024)),
                ('name', models.CharField(default='', max_length=1024)),
                ('email', models.EmailField(default='', max_length=1024)),
                ('contact', models.CharField(default='', max_length=12)),
                ('requirements', models.CharField(default='', max_length=2500)),
            ],
        ),
    ]
