# Generated by Django 3.2.5 on 2022-05-14 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sugartownapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userfaceimage',
        ),
    ]
