# Generated by Django 3.2.5 on 2022-05-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugartownapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_contactinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=1024)),
                ('name', models.CharField(default='', max_length=1024)),
                ('email', models.EmailField(default='', max_length=1024)),
                ('message', models.CharField(default='', max_length=2500)),
            ],
        ),
    ]
