# Generated by Django 3.2.5 on 2022-05-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugartownapp', '0002_user_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsletter_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=1024)),
                ('email', models.EmailField(default='', max_length=1024)),
            ],
        ),
    ]
