# Generated by Django 3.2.5 on 2022-05-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugartownapp', '0003_userfaceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfaceid',
            name='username',
            field=models.CharField(default='', max_length=1024, unique=True),
        ),
    ]
