# Generated by Django 3.2.5 on 2022-05-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugartownapp', '0004_user_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_cart',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
