# Generated by Django 3.2.5 on 2022-05-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugartownapp', '0005_user_cart_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='discount_coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(default='', max_length=1024)),
                ('couponcode', models.CharField(default='', max_length=1024)),
            ],
        ),
    ]
