# Generated by Django 3.2.5 on 2022-05-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugartownapp', '0006_discount_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount_coupons',
            name='validprice',
            field=models.IntegerField(default=0),
        ),
    ]
