# Generated by Django 3.2.5 on 2022-05-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugartownapp', '0007_discount_coupons_validprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount_coupons',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
    ]
