# Generated by Django 3.2.5 on 2022-05-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugartownapp', '0008_discount_coupons_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_cart',
            name='total_cart_value',
            field=models.IntegerField(default=0),
        ),
    ]
