# Generated by Django 3.2.5 on 2022-05-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugartownapp', '0009_user_cart_total_cart_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_cart_value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=1024)),
                ('total_cart_value', models.IntegerField(default=0)),
            ],
        ),
    ]
