# Generated by Django 3.2.5 on 2022-05-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugartownapp', '0010_user_cart_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_cart_value',
            name='total_cart_value',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
