# Generated by Django 3.2.5 on 2022-05-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugartownapp', '0011_alter_user_cart_value_total_cart_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_cart_value',
            name='coupon_applied',
            field=models.CharField(default='', max_length=1024, null=True),
        ),
    ]
