# Generated by Django 3.2.5 on 2022-05-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugartownapp', '0012_user_cart_value_coupon_applied'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=1024)),
                ('wallet_balance', models.IntegerField(default=0)),
            ],
        ),
    ]
