# Generated by Django 3.2.5 on 2022-05-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugartownapp', '0015_alter_user_cart_value_coupon_applied'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=1024)),
                ('fname', models.CharField(default='', max_length=1024)),
                ('lname', models.CharField(default='', max_length=1024)),
                ('country', models.CharField(default='', max_length=1024)),
                ('address', models.CharField(default='', max_length=1024)),
                ('city', models.CharField(default='', max_length=1024)),
                ('postcode', models.CharField(default='', max_length=1024)),
                ('phone', models.CharField(default='', max_length=12)),
                ('email', models.EmailField(default='', max_length=1024)),
                ('total_payable_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='userorderdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=1024)),
                ('product_name', models.CharField(default='', max_length=1024)),
                ('quantity', models.CharField(default='', max_length=1024)),
            ],
        ),
    ]
