# Generated by Django 3.2.5 on 2022-05-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugartownapp', '0016_user_order_userorderdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_order',
            old_name='address',
            new_name='apartment',
        ),
        migrations.AddField(
            model_name='user_order',
            name='street',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
