# Generated by Django 3.2.5 on 2022-05-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugartownapp', '0018_user_order_orderplaced_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_order',
            name='orderplaced_on',
            field=models.DateTimeField(),
        ),
    ]
